name: Build

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  build:
    strategy:
      matrix:
        platform: [ubuntu-latest]
        otp-version: [25, 26]
    runs-on: ${{ matrix.platform }}
    container:
      image: erlang:${{ matrix.otp-version }}
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Compile
      run: rebar3 compile
    - name: Run EUnit Tests
      run: rebar3 eunit
    - name: Run Common Tests
      run: rebar3 ct
    - name: Upload Common Test result
      if: ${{ always() }}
      uses: actions/upload-artifact@v3
      with:
        name: Common Test ${{ matrix.otp-version }}
        path: _build/test/logs/**
        retention-days: 3
